<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>StaeryCMS.Core</RootNamespace>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Markdig" Version="1.4.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="StaeryCMS.Core.Tests" />
  </ItemGroup>

</Project>
